default_context:
  project_name: 'abtool_api'
  project_slug: 'abtool_api'
  domain_main: 'abtool_api.com'
  domain_staging: 'stag.abtool_api.com'
  docker_swarm_stack_name_main: 'abtool_api-com'
  docker_swarm_stack_name_staging: 'stag-abtool_api-com'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  first_superuser: 'gokul'
  first_superuser_password: 'gokul'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.abtool_api.com", "https://stag.abtool_api.com", "https://abtool_api.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@abtool_api.com'
  postgres_password: 'abtool123'
  pgadmin_default_user: 'gokul'
  pgadmin_default_user_password: 'gokul'
  traefik_constraint_tag: 'abtool_api.com'
  traefik_constraint_tag_staging: 'stag.abtool_api.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:gokul'
  sentry_dsn: 'https://7fec5b8edcff4959a55b19ad3193ea66@o1181426.ingest.sentry.io/4504621140672512'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
